import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const expected='https://script.google.com/macros/s/AKfycbyJ9mmjtsX75i49WfmMQiAKf2dp3JGygqdPbYdZ8kp2O3bUIFIIo1Lf8zL7lH39GEJK/exec';
for(const text of ['共享动作数据识别表','任何人上传后','所有打开链接的人都能看到并下载原文件',expected,'getRegistrations','unregister','location.replace'])if(!html.includes(text))throw new Error(`redirect_missing:${text}`);
const js=html.split('<script>')[1].split('</script>')[0];
new vm.Script(js);
const response=await fetch(expected,{redirect:'follow'});
if(!response.ok)throw new Error(`shared_app_http_${response.status}`);
const body=await response.text();
if(!body.includes('共享动作数据识别表'))throw new Error('shared_app_title_missing');
console.log(`PUBLIC_REDIRECT_RESULT=PASS target=${expected} access=anyone storage=GoogleSheet files=GoogleDrive formats=BVH,PKL,GZ,ZIP`);
