import { gunzipSync, unzipSync } from 'fflate';

type Format='BVH'|'PKL';
type MotionMeta={format:Format;frames:number|null;fps:number|null;durationMs:number|null};
type StoredRow=MotionMeta&{id:string;name:string;size:number;sha256:string;sourceArchive:string;createdAt:string;blob:Blob};
type ArchiveEntry={name:string;data:Uint8Array};

const DB_NAME='motion-file-table-v1',STORE='files';
const supported=new Set(['bvh','pkl']);
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const extOf=(name:string)=>name.split('.').pop()?.toLowerCase()??'';
const baseName=(path:string)=>path.replaceAll('\\','/').split('/').filter(Boolean).pop()||path;
const isZip=(b:Uint8Array)=>b.length>4&&b[0]===0x50&&b[1]===0x4b&&(b[2]===0x03||b[2]===0x05||b[2]===0x07);
const isGzip=(b:Uint8Array)=>b.length>3&&b[0]===0x1f&&b[1]===0x8b;
const sane=(value:number|null,min:number,max:number)=>value!==null&&Number.isFinite(value)&&value>=min&&value<=max?value:null;

function parseBvh(bytes:Uint8Array):MotionMeta{
  const text=new TextDecoder('utf-8',{fatal:false}).decode(bytes);
  const frames=sane(Number(text.match(/\bFrames\s*:\s*(\d+)/i)?.[1]??NaN),1,2_000_000_000);
  const frameTime=sane(Number(text.match(/\bFrame\s+Time\s*:\s*([\d.eE+-]+)/i)?.[1]??NaN),1e-8,3600);
  const fps=frameTime?1/frameTime:null;
  return {format:'BVH',frames,fps,durationMs:frames&&fps?frames/fps*1000:null};
}
function findAscii(bytes:Uint8Array,needle:string,start=0){const target=new TextEncoder().encode(needle);outer:for(let i=start;i<=bytes.length-target.length;i++){for(let j=0;j<target.length;j++)if(bytes[i+j]!==target[j])continue outer;return i}return -1}
const int32LE=(b:Uint8Array,o:number)=>new DataView(b.buffer,b.byteOffset+o,4).getInt32(0,true);
const uint32LE=(b:Uint8Array,o:number)=>new DataView(b.buffer,b.byteOffset+o,4).getUint32(0,true);
function uint64LE(b:Uint8Array,o:number){const n=Number(new DataView(b.buffer,b.byteOffset+o,8).getBigUint64(0,true));return Number.isSafeInteger(n)?n:-1}
function readNumberOpcode(bytes:Uint8Array,offset:number):{value:number;next:number}|null{const op=bytes[offset];if(op===0x4b&&offset+1<bytes.length)return{value:bytes[offset+1],next:offset+2};if(op===0x4d&&offset+2<bytes.length)return{value:bytes[offset+1]|bytes[offset+2]<<8,next:offset+3};if(op===0x4a&&offset+4<bytes.length)return{value:int32LE(bytes,offset+1),next:offset+5};if(op===0x47&&offset+8<bytes.length)return{value:new DataView(bytes.buffer,bytes.byteOffset+offset+1,8).getFloat64(0,false),next:offset+9};if(op===0x8a&&offset+1<bytes.length){const len=bytes[offset+1];if(len>6||offset+2+len>bytes.length)return null;let value=0;for(let i=0;i<len;i++)value+=bytes[offset+2+i]*2**(8*i);return{value,next:offset+2+len}}return null}
function numberAfterKey(bytes:Uint8Array,key:string){const at=findAscii(bytes,key);if(at<0)return null;for(let i=at+key.length;i<Math.min(bytes.length,at+key.length+96);i++){const hit=readNumberOpcode(bytes,i);if(hit)return hit.value}return null}
function skipBlob(bytes:Uint8Array,offset:number){const op=bytes[offset];if((op===0x96||op===0x8e)&&offset+8<bytes.length){const n=uint64LE(bytes,offset+1);return n>=0&&offset+9+n<=bytes.length?offset+9+n:-1}if(op===0x42&&offset+4<bytes.length){const n=uint32LE(bytes,offset+1);return offset+5+n<=bytes.length?offset+5+n:-1}return-1}
function firstArrayShape(bytes:Uint8Array,key:string){const at=findAscii(bytes,key);if(at<0)return null;let payloadEnd=-1;for(let i=at+key.length;i<Math.min(bytes.length,at+key.length+512);i++){const skipped=skipBlob(bytes,i);if(skipped>0){payloadEnd=skipped;break}}if(payloadEnd<0)return null;const recent:number[]=[];for(let i=payloadEnd;i<Math.min(bytes.length,payloadEnd+8192);){const number=readNumberOpcode(bytes,i);if(number){recent.push(number.value);if(recent.length>4)recent.shift();i=number.next;continue}const op=bytes[i];if(op===0x86&&recent.length>=2){const frames=recent.at(-2)!,width=recent.at(-1)!;if(frames>=1&&frames<=2_000_000_000&&width>=1&&width<=100_000)return[frames,width]as const}if(op===0x95&&i+8<bytes.length){i+=9;continue}if(op===0x8c&&i+1<bytes.length){i+=2+bytes[i+1];continue}if((op===0x58||op===0x42)&&i+4<bytes.length){i+=5+uint32LE(bytes,i+1);continue}if((op===0x8d||op===0x8e||op===0x96)&&i+8<bytes.length){const n=uint64LE(bytes,i+1);i+=n>=0?9+n:1;continue}i++}return null}
function parsePkl(bytes:Uint8Array):MotionMeta{const fps=sane(numberAfterKey(bytes,'fps')??numberAfterKey(bytes,'frame_rate')??numberAfterKey(bytes,'framerate'),.001,100_000);let frames:number|null=null;for(const key of ['root_trans_offset','dof','root_rot','contact_mask']){const shape=firstArrayShape(bytes,key);if(shape){frames=sane(shape[0],1,2_000_000_000);break}}return{format:'PKL',frames,fps,durationMs:frames&&fps?frames/fps*1000:null}}
function parseMotion(name:string,bytes:Uint8Array){if(extOf(name)==='bvh')return parseBvh(bytes);if(extOf(name)==='pkl')return parsePkl(bytes);throw new Error('不支持的文件格式')}

const tarText=(b:Uint8Array,s:number,l:number)=>new TextDecoder().decode(b.subarray(s,s+l)).replace(/\0.*$/s,'').trim();
function extractTar(bytes:Uint8Array){const files:ArchiveEntry[]=[];let offset=0,pendingName='';while(offset+512<=bytes.length){const header=bytes.subarray(offset,offset+512);if(header.every(v=>v===0))break;const name=pendingName||[tarText(header,345,155),tarText(header,0,100)].filter(Boolean).join('/');pendingName='';const size=Number.parseInt(tarText(header,124,12)||'0',8);if(!Number.isFinite(size)||size<0||offset+512+size>bytes.length)throw new Error('TAR 文件结构无效');const type=String.fromCharCode(header[156]||48),data=bytes.slice(offset+512,offset+512+size);if(type==='L')pendingName=new TextDecoder().decode(data).replace(/\0.*$/s,'');else if(type==='0'||type==='\0')files.push({name,data});offset+=512+Math.ceil(size/512)*512}return files}
function expandArchive(name:string,bytes:Uint8Array):ArchiveEntry[]{const ext=extOf(name);if(ext==='zip'||isZip(bytes))return Object.entries(unzipSync(bytes)).map(([entryName,data])=>({name:entryName,data})).filter(e=>supported.has(extOf(e.name)));if(ext==='gz'||isGzip(bytes)){const data=gunzipSync(bytes),uncompressed=name.replace(/\.gz$/i,'');if(extOf(uncompressed)==='tar')return extractTar(data).filter(e=>supported.has(extOf(e.name)));if(supported.has(extOf(uncompressed)))return[{name:baseName(uncompressed),data}];const head=new TextDecoder().decode(data.subarray(0,64));if(/^\s*HIERARCHY\b/i.test(head))return[{name:`${baseName(uncompressed)}.bvh`,data}];if(data[0]===0x80&&data[1]>=2&&data[1]<=5)return[{name:`${baseName(uncompressed)}.pkl`,data}];return extractTar(data).filter(e=>supported.has(extOf(e.name)))}return supported.has(ext)?[{name:baseName(name),data:bytes}]:[]}

function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function rows(){const db=await openDb();return new Promise<StoredRow[]>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));request.onerror=()=>reject(request.error)})}
async function put(row:StoredRow){const db=await openDb();return new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,'readwrite').objectStore(STORE).put(row);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
async function clearRows(){const db=await openDb();return new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,'readwrite').objectStore(STORE).clear();request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
async function sha256(bytes:Uint8Array){const copy=new Uint8Array(bytes);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',copy.buffer))].map(v=>v.toString(16).padStart(2,'0')).join('')}
const fileSize=(n:number)=>n<1024?`${n} B`:n<1024**2?`${(n/1024).toFixed(1)} KB`:`${(n/1024**2).toFixed(2)} MB`;
const duration=(ms:number|null)=>{if(ms==null)return'—';const total=ms/1000,h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${s.toFixed(2).padStart(5,'0')}`};
const escapeHtml=(s:string)=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const csvCell=(value:string|number|null)=>`"${(value??'').toString().replaceAll('"','""')}"`;
function showNotice(text:string){const el=$<HTMLDivElement>('notice');el.textContent=text;el.classList.toggle('hidden',!text)}

async function render(){const data=await rows(),body=$<HTMLTableSectionElement>('file-table');$('total-files').textContent=String(data.length);const recognized=data.filter(r=>r.frames&&r.fps);$('recognized-files').textContent=String(recognized.length);$('average-fps').textContent=recognized.length?String(Number((recognized.reduce((n,r)=>n+(r.fps||0),0)/recognized.length).toFixed(2))):'—';$('total-duration').textContent=duration(data.reduce((n,r)=>n+(r.durationMs||0),0));$<HTMLButtonElement>('export-button').disabled=!data.length;$<HTMLButtonElement>('clear-button').disabled=!data.length;if(!data.length){body.innerHTML='<tr><td colspan="6" class="empty"><b>表格还是空的</b><span>把动作文件放到上方，识别结果会自动出现在这里</span></td></tr>';return}body.innerHTML=data.map(r=>`<tr><td><a href="#" data-download="${r.id}"><span class="file-icon">${r.format[0]}</span><span>${escapeHtml(r.name)}${r.sourceArchive?`<small>来自 ${escapeHtml(r.sourceArchive)}</small>`:''}</span></a></td><td><span class="format-pill format-${r.format.toLowerCase()}">${r.format}</span></td><td>${duration(r.durationMs)}</td><td>${fileSize(r.size)}</td><td>${r.fps==null?'待确认':`${Number(r.fps.toFixed(4))} fps`}</td><td>${r.frames??'待确认'}</td></tr>`).join('');body.querySelectorAll<HTMLAnchorElement>('[data-download]').forEach(a=>a.onclick=async e=>{e.preventDefault();const row=data.find(r=>r.id===a.dataset.download);if(!row)return;const url=URL.createObjectURL(row.blob),link=document.createElement('a');link.href=url;link.download=row.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})}

async function ingest(selected:File[]){const progress=$<HTMLDivElement>('progress'),button=$<HTMLButtonElement>('choose-button');button.disabled=true;showNotice('');const expanded:{name:string;data:Uint8Array;sourceArchive:string}[]=[],errors:string[]=[];for(const source of selected){try{if(source.size>500*1024*1024)throw new Error('文件超过 500 MB');const bytes=new Uint8Array(await source.arrayBuffer()),entries=expandArchive(source.name,bytes);if(entries.length>10000||entries.reduce((n,e)=>n+e.data.byteLength,0)>2*1024**3)throw new Error('解压内容过大');if(!entries.length)throw new Error('文件包内没有 BVH 或 PKL 文件');for(const entry of entries)expanded.push({name:baseName(entry.name),data:entry.data,sourceArchive:['gz','zip'].includes(extOf(source.name))?source.name:''})}catch(error){errors.push(`${source.name}：${error instanceof Error?error.message:'读取失败'}`)}}progress.classList.remove('hidden');let done=0;for(const item of expanded){progress.innerHTML=`<div><b>正在识别 ${escapeHtml(item.name)}</b><span>${done} / ${expanded.length}</span></div><div class="progress-track"><i style="width:${expanded.length?done/expanded.length*100:100}%"></i></div>`;await new Promise(requestAnimationFrame);try{const hash=await sha256(item.data),meta=parseMotion(item.name,item.data);await put({...meta,id:hash,name:item.name,size:item.data.byteLength,sha256:hash,sourceArchive:item.sourceArchive,createdAt:new Date().toISOString(),blob:new Blob([new Uint8Array(item.data)],{type:'application/octet-stream'})})}catch(error){errors.push(`${item.name}：${error instanceof Error?error.message:'识别失败'}`)}done++}progress.innerHTML=`<div><b>处理完成</b><span>${done} / ${expanded.length}</span></div><div class="progress-track"><i style="width:100%"></i></div>${errors.length?`<details open><summary>${errors.length} 个文件需要检查</summary>${errors.map(e=>`<p>${escapeHtml(e)}</p>`).join('')}</details>`:''}`;button.disabled=false;await render();showNotice(errors.length?`处理完成：${expanded.length-errors.length} 个成功，${errors.length} 个失败`:`已自动识别并保存 ${expanded.length} 个文件`) }

const input=$<HTMLInputElement>('file-input'),dropzone=$<HTMLDivElement>('dropzone');$('choose-button').onclick=()=>input.click();input.onchange=()=>{const files=Array.from(input.files||[]);if(files.length)void ingest(files);input.value=''};dropzone.ondragenter=e=>{e.preventDefault();dropzone.classList.add('is-dragging')};dropzone.ondragover=e=>e.preventDefault();dropzone.ondragleave=()=>dropzone.classList.remove('is-dragging');dropzone.ondrop=e=>{e.preventDefault();dropzone.classList.remove('is-dragging');const files=Array.from(e.dataTransfer?.files||[]);if(files.length)void ingest(files)};
$('export-button').onclick=async()=>{const data=await rows(),lines=[['文件名称','文件格式','文件时长','文件大小（字节）','文件数据帧率','帧数','SHA-256'],...data.map(r=>[r.name,r.format,duration(r.durationMs),r.size,r.fps==null?'':Number(r.fps.toFixed(6)),r.frames??'',r.sha256])].map(line=>line.map(csvCell).join(','));const url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='动作数据识别表.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('clear-button').onclick=async()=>{if(confirm('确定清空当前浏览器中保存的文件和表格吗？')){await clearRows();await render();showNotice('已清空当前浏览器中的表格')}};
void render().catch(()=>showNotice('当前浏览器不支持本地文件表，请升级浏览器后重试'));
